### ISSUE TITLE
Downloads count is always 0

### ISSUE THREAD

**Issue by Rivolvan** [rootasjey/unsplasharp#1]
The downloads count of the Photo object is always zero. This information can be sometimes useful when suggesting photos to users.

**Comment by rootasjey** [comment]
On which API endpoint/method ?
If it's on ```ListPhotos``` endpoint/method, the information isn't available  right away. You'll need to retrieve a single photo from its ID to get the downloads count.

You can test by yourself there:
* [```client.ListPhotos()```](https://api.unsplash.com/photos?client_id=b27797f08021cb0d84672e38530613898facf6d4b06c62ec7dd5a2912c9a4438)
* [```client.GetPhoto("m4z1GFECZrU")```](https://api.unsplash.com/photos/m4z1GFECZrU?client_id=b27797f08021cb0d84672e38530613898facf6d4b06c62ec7dd5a2912c9a4438)

**Comment by Rivolvan** [comment]
I was using the
`SearchPhotos(query)`
endpoint. Is searching for photos this way won't get a downloads count?

**Comment by rootasjey** [comment]
You're welcome :)

Okay, so unfortunately you won't get the downloads count on the search results. But as I mentioned in my previous comment, you can get it with the ```client.GetPhoto("id")```. It can be expensive if you want to display downloads count on each item of the search results, but I can't think of a better solution at the moment.

[API doc](https://unsplash.com/documentation#search-photos)
[`client.SearchPhotos("sky")`](https://api.unsplash.com/search/photos?query=sky&client_id=b27797f08021cb0d84672e38530613898facf6d4b06c62ec7dd5a2912c9a4438)
