### ISSUE TITLE
HttpClient handling

### ISSUE THREAD

**Issue by mattheww-freshview** [rootasjey/unsplasharp#10]
When reviewing your code (since we are starting to use it in some upcoming work) I noticed that the usage of HttpClient _might_ be a problem (see https://www.aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/ for context).

I've created a PR that will hopefully help, as well as deleted dead tests and fixing broken tests. https://github.com/rootasjey/unsplasharp/pull/9

Please let me know if you have any questions.

**Comment by rootasjey** [comment]
Thank you.
Solved with your PR https://github.com/rootasjey/unsplasharp/pull/9
