### ISSUE TITLE
client.RateLimitRemaining is always 0

### ISSUE THREAD

**Issue by nicolasguzca** [rootasjey/unsplasharp#3]
Hi! First of all thank you for this library.

For some reason client.RateLImitRemaining is always 0. I am authorized since I have been able get images from the api.

This is what I am doing:
 ```
client = new UnsplasharpClient(accessKey);
            string imageURL = "";
            var thecount = client.RateLimitRemaining;
```

var thecount is always cero.

**Comment by rootasjey** [comment]
Hello @nicolasguzca, you have to send a request (e.g. getting a random photo) to get the actual `RateLimitRemaining`. When you instantiate the client, no request is sent, so the `RateLimitRemaining` isn't the real one (and is 0 by default).

```
var client = new UnsplasharpClient("accessKey");
var randomPhoto = client. GetRandomPhoto();
var rateLimitRemaining = client.RateLimitRemaining; // should be the real one from the Unsplash server
```

Doing that, you should get the real remaining count.

Let me know if that doesn't work for you.
