### ISSUE TITLE
Fetch issue

### ISSUE THREAD

**Issue by theclai** [rootasjey/unsplasharp#6]
Issue with Fetch method 

-->  http.DefaultRequestHeaders.Authorization =
                new AuthenticationHeaderValue("client_id", ApplicationId);
            HttpResponseMessage response = null;

it should be https://api.unsplash.com/photos/?client_id=YOUR_ACCESS_KEY
![Screen Shot 08-13-20 at 08 22 AM](https://user-images.githubusercontent.com/1164970/90080830-3ed3cc00-dd3e-11ea-8974-8dd6f1ea1b55.PNG)

**Comment by rootasjey** [comment]
The new version should solve this issue. Can you test a give a feedback ?
https://www.nuget.org/packages/unsplasharp.api/0.5.8
